## Import Polars

In [1]:
# pip install polars
# poetry add polars
# uv add polars

In [2]:
import polars as pl

## Read Data into DataFrame

In [3]:
COLUMN_NAMES = [
        "id", "price", "date", "postcode", "property_type",
        "old_new", "duration", "paon", "saon", "street",
        "locality", "town_city", "district", "county",
        "ppd_category", "record_type",
    ]

In [4]:
land_registry_data = pl.read_csv(
    source="../../data/land_registry_data/pp-*.csv",
    has_header=False,
    new_columns=COLUMN_NAMES,
    infer_schema=True,
    null_values=[""],
)

In [5]:
land_registry_data.sample(5)

shape: (5, 16)
┌────────────┬────────┬────────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ id         ┆ price  ┆ date       ┆ postcode ┆ … ┆ district   ┆ county    ┆ ppd_categ ┆ record_ty │
│ ---        ┆ ---    ┆ ---        ┆ ---      ┆   ┆ ---        ┆ ---       ┆ ory       ┆ pe        │
│ str        ┆ i64    ┆ str        ┆ str      ┆   ┆ str        ┆ str       ┆ ---       ┆ ---       │
│            ┆        ┆            ┆          ┆   ┆            ┆           ┆ str       ┆ str       │
╞════════════╪════════╪════════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ {1775CCF7- ┆ 240000 ┆ 2023-12-04 ┆ TN13 3TQ ┆ … ┆ SEVENOAKS  ┆ KENT      ┆ A         ┆ A         │
│ 42EE-38BA- ┆        ┆ 00:00      ┆          ┆   ┆            ┆           ┆           ┆           │
│ E063-4704A ┆        ┆            ┆          ┆   ┆            ┆           ┆           ┆           │
│ …          ┆        ┆            ┆          ┆   ┆            ┆           ┆           ┆           │
│ {5CF9903C- ┆ 269950 ┆ 2017-10-09 ┆ CF23 8LG ┆ … ┆ CARDIFF    ┆ CARDIFF   ┆ A         ┆ A         │
│ A18C-7F13- ┆        ┆ 00:00      ┆          ┆   ┆            ┆           ┆           ┆           │
│ E053-6C04A ┆        ┆            ┆          ┆   ┆            ┆           ┆           ┆           │
│ …          ┆        ┆            ┆          ┆   ┆            ┆           ┆           ┆           │
│ {8F1B26BD- ┆ 293995 ┆ 2019-04-26 ┆ NE61 2FS ┆ … ┆ NORTHUMBER ┆ NORTHUMBE ┆ A         ┆ A         │
│ F4E1-53DB- ┆        ┆ 00:00      ┆          ┆   ┆ LAND       ┆ RLAND     ┆           ┆           │
│ E053-6C04A ┆        ┆            ┆          ┆   ┆            ┆           ┆           ┆           │
│ …          ┆        ┆            ┆          ┆   ┆            ┆           ┆           ┆           │
│ {4777E0AF- ┆ 230000 ┆ 2025-08-20 ┆ WR2 6JU  ┆ … ┆ WORCESTER  ┆ WORCESTER ┆ B         ┆ A         │
│ 8EDF-5D59- ┆        ┆ 00:00      ┆          ┆   ┆            ┆ SHIRE     ┆           ┆           │
│ E063-4804A ┆        ┆            ┆          ┆   ┆            ┆           ┆           ┆           │
│ …          ┆        ┆            ┆          ┆   ┆            ┆           ┆           ┆           │
│ {E53EDD2E- ┆ 335000 ┆ 2022-06-28 ┆ KT22 7LD ┆ … ┆ MOLE       ┆ SURREY    ┆ A         ┆ A         │
│ 4227-83EC- ┆        ┆ 00:00      ┆          ┆   ┆ VALLEY     ┆           ┆           ┆           │
│ E053-6B04A ┆        ┆            ┆          ┆   ┆            ┆           ┆           ┆           │
│ …          ┆        ┆            ┆          ┆   ┆            ┆           ┆           ┆           │
└────────────┴────────┴────────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [6]:
land_registry_data.describe()

shape: (9, 17)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ statistic ┆ id        ┆ price     ┆ date      ┆ … ┆ district ┆ county    ┆ ppd_categ ┆ record_ty │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---      ┆ ---       ┆ ory       ┆ pe        │
│ str       ┆ str       ┆ f64       ┆ str       ┆   ┆ str      ┆ str       ┆ ---       ┆ ---       │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ str       ┆ str       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ count     ┆ 10002480  ┆ 1.000248e ┆ 10002480  ┆ … ┆ 10002480 ┆ 10002480  ┆ 10002480  ┆ 10002480  │
│           ┆           ┆ 7         ┆           ┆   ┆          ┆           ┆           ┆           │
│ null_coun ┆ 0         ┆ 0.0       ┆ 0         ┆ … ┆ 0        ┆ 0         ┆ 0         ┆ 0         │
│ t         ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ mean      ┆ null      ┆ 372035.51 ┆ null      ┆ … ┆ null     ┆ null      ┆ null      ┆ null      │
│           ┆           ┆ 4483      ┆           ┆   ┆          ┆           ┆           ┆           │
│ std       ┆ null      ┆ 1.6258e6  ┆ null      ┆ … ┆ null     ┆ null      ┆ null      ┆ null      │
│ min       ┆ {01EB45EF ┆ 1.0       ┆ 2016-01-0 ┆ … ┆ ADUR     ┆ BATH AND  ┆ A         ┆ A         │
│           ┆ -612C-40F ┆           ┆ 1 00:00   ┆   ┆          ┆ NORTH     ┆           ┆           │
│           ┆ 3-E063-47 ┆           ┆           ┆   ┆          ┆ EAST      ┆           ┆           │
│           ┆ 04A…      ┆           ┆           ┆   ┆          ┆ SOMERSET  ┆           ┆           │
│ 25%       ┆ null      ┆ 160000.0  ┆ null      ┆ … ┆ null     ┆ null      ┆ null      ┆ null      │
│ 50%       ┆ null      ┆ 250000.0  ┆ null      ┆ … ┆ null     ┆ null      ┆ null      ┆ null      │
│ 75%       ┆ null      ┆ 390000.0  ┆ null      ┆ … ┆ null     ┆ null      ┆ null      ┆ null      │
│ max       ┆ {FFA361DB ┆ 9e8       ┆ 2025-12-3 ┆ … ┆ YORK     ┆ YORK      ┆ B         ┆ A         │
│           ┆ -9CCE-8A0 ┆           ┆ 1 00:00   ┆   ┆          ┆           ┆           ┆           │
│           ┆ 3-E053-48 ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆ 04A…      ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

In [7]:
land_registry_data = (
    land_registry_data
    .with_columns(
        pl.col("date").str.to_date(format="%Y-%m-%d %H:%M"),
    )
)

In [8]:
land_registry_data = land_registry_data.with_columns(
    pl.col("property_type").replace({
        "D": "Detached",
        "S": "Semi-Detached",
        "T": "Terraced",
        "F": "Flat",
        "O": "Other",
    }).alias("property_type")
)

In [9]:
land_registry_data["property_type"].value_counts()

shape: (5, 2)
┌───────────────┬─────────┐
│ property_type ┆ count   │
│ ---           ┆ ---     │
│ str           ┆ u32     │
╞═══════════════╪═════════╡
│ Other         ┆ 582196  │
│ Terraced      ┆ 2696606 │
│ Detached      ┆ 2303875 │
│ Flat          ┆ 1794725 │
│ Semi-Detached ┆ 2625078 │
└───────────────┴─────────┘

In [10]:
land_registry_data = land_registry_data.filter(pl.col("property_type") != "Other")

In [11]:
land_registry_data = (
    land_registry_data
    .with_columns(
        pl.col("date").dt.year().alias("year"),
    )
)

In [12]:
land_registry_data.select(["id", "date", "year", "property_type", "price"])

shape: (9_420_284, 5)
┌─────────────────────────────────┬────────────┬──────┬───────────────┬────────┐
│ id                              ┆ date       ┆ year ┆ property_type ┆ price  │
│ ---                             ┆ ---        ┆ ---  ┆ ---           ┆ ---    │
│ str                             ┆ date       ┆ i32  ┆ str           ┆ i64    │
╞═════════════════════════════════╪════════════╪══════╪═══════════════╪════════╡
│ {3E0330F0-76C8-8D89-E050-A8C06… ┆ 2016-09-21 ┆ 2016 ┆ Flat          ┆ 103750 │
│ {3E0330F0-76C9-8D89-E050-A8C06… ┆ 2016-09-16 ┆ 2016 ┆ Semi-Detached ┆ 165000 │
│ {3E0330F0-76CA-8D89-E050-A8C06… ┆ 2016-09-02 ┆ 2016 ┆ Semi-Detached ┆ 90000  │
│ {3E0330F0-76CB-8D89-E050-A8C06… ┆ 2016-08-22 ┆ 2016 ┆ Terraced      ┆ 105000 │
│ {3E0330F0-76CC-8D89-E050-A8C06… ┆ 2016-08-30 ┆ 2016 ┆ Semi-Detached ┆ 67500  │
│ …                               ┆ …          ┆ …    ┆ …             ┆ …      │
│ {36A61A95-56AD-DEF2-E063-4704A… ┆ 2025-05-22 ┆ 2025 ┆ Semi-Detached ┆ 267500 │
│ {36A61A95-56AE-DEF2-E063-4704A… ┆ 2025-04-29 ┆ 2025 ┆ Semi-Detached ┆ 230000 │
│ {36A61A95-56B0-DEF2-E063-4704A… ┆ 2025-04-30 ┆ 2025 ┆ Flat          ┆ 177500 │
│ {36A61A95-56B2-DEF2-E063-4704A… ┆ 2025-05-02 ┆ 2025 ┆ Terraced      ┆ 113501 │
│ {36A61A95-56B7-DEF2-E063-4704A… ┆ 2025-03-31 ┆ 2025 ┆ Terraced      ┆ 250000 │
└─────────────────────────────────┴────────────┴──────┴───────────────┴────────┘

In [13]:
annual_price_by_property_type = (
    land_registry_data
    .group_by(["year", "property_type"])
    .agg(
        pl.col("price").median().alias("median_price")
    )
    .sort(["year", "property_type"])
)

In [14]:
annual_price_by_property_type

shape: (40, 3)
┌──────┬───────────────┬──────────────┐
│ year ┆ property_type ┆ median_price │
│ ---  ┆ ---           ┆ ---          │
│ i32  ┆ str           ┆ f64          │
╞══════╪═══════════════╪══════════════╡
│ 2016 ┆ Detached      ┆ 306000.0     │
│ 2016 ┆ Flat          ┆ 200000.0     │
│ 2016 ┆ Semi-Detached ┆ 187500.0     │
│ 2016 ┆ Terraced      ┆ 169000.0     │
│ 2017 ┆ Detached      ┆ 322500.0     │
│ …    ┆ …             ┆ …            │
│ 2024 ┆ Terraced      ┆ 220000.0     │
│ 2025 ┆ Detached      ┆ 416100.5     │
│ 2025 ┆ Flat          ┆ 230000.0     │
│ 2025 ┆ Semi-Detached ┆ 270000.0     │
│ 2025 ┆ Terraced      ┆ 225000.0     │
└──────┴───────────────┴──────────────┘

## Visualise the results

In [15]:
import plotly.express as px

In [16]:
px.line(
    annual_price_by_property_type,
    x="year",
    y="median_price",
    color="property_type",
    markers=True,
    title="Median Price by Year and Property Type",
    width=800,
    height=600,
)

In [17]:
annual_price_by_property_type.write_delta("../../data/price_paid_insights/annual_price_by_property_type", mode="overwrite")

In [18]:
lazy_frame = (
    pl.scan_csv(
    source="../../data/land_registry_data/pp-*.csv",
    has_header=False,
    new_columns=COLUMN_NAMES,
    infer_schema=True,
    null_values=[""])
    .with_columns(
        pl.col("date").str.to_date(format="%Y-%m-%d %H:%M"),
    )
    .with_columns(
        pl.col("property_type").replace({
            "D": "Detached",
            "S": "Semi-Detached",
            "T": "Terraced",
            "F": "Flat",
            "O": "Other",
        }).alias("property_type")
    )
    .filter(pl.col("property_type") != "Other")
    .with_columns(
        pl.col("date").dt.year().alias("year")
    )
    .group_by(["year", "property_type"])
    .agg(
        pl.col("price").median().alias("median_price")
    )
    .sort(["year", "property_type"])
)

In [19]:
lazy_frame

In [20]:
print(lazy_frame.explain())

SORT BY [col("year"), col("property_type")]
  AGGREGATE[maintain_order: false]
    [col("price").median().alias("median_price")] BY [col("year"), col("property_type")]
    FROM
     WITH_COLUMNS:
     [col("date").dt.year().alias("year")]
      FILTER [(col("property_type")) != ("Other")]
      FROM
         WITH_COLUMNS:
         [col("date").str.strptime(["raise"]), col("property_type").replace([["D", "S", … "O"], ["Detached", "Semi-Detached", … "Other"]])]
          Csv SCAN [../../data/land_registry_data/pp-2016.csv, ... 9 other sources]
          PROJECT 3/16 COLUMNS
          ESTIMATED ROWS: 1066856

In [21]:
lazy_frame.collect()

shape: (40, 3)
┌──────┬───────────────┬──────────────┐
│ year ┆ property_type ┆ median_price │
│ ---  ┆ ---           ┆ ---          │
│ i32  ┆ str           ┆ f64          │
╞══════╪═══════════════╪══════════════╡
│ 2016 ┆ Detached      ┆ 306000.0     │
│ 2016 ┆ Flat          ┆ 200000.0     │
│ 2016 ┆ Semi-Detached ┆ 187500.0     │
│ 2016 ┆ Terraced      ┆ 169000.0     │
│ 2017 ┆ Detached      ┆ 322500.0     │
│ …    ┆ …             ┆ …            │
│ 2024 ┆ Terraced      ┆ 220000.0     │
│ 2025 ┆ Detached      ┆ 416100.5     │
│ 2025 ┆ Flat          ┆ 230000.0     │
│ 2025 ┆ Semi-Detached ┆ 270000.0     │
│ 2025 ┆ Terraced      ┆ 225000.0     │
└──────┴───────────────┴──────────────┘

In [22]:
# Stream data to parquet
lazy_frame.sink_parquet("../../data/price_paid_insights/land_registry_data.parquet")